language: cpp

install: |
  sudo apt-get update
  sudo apt-get build-dep gdb
  sudo apt-get install systemtap-sdt-dev
  cd "$TRAVIS_BUILD_DIR"
  mkdir _build
  cd _build
  ../configure --with-sysroot=/
  cd gdb/
  make -j"$(nproc)"
  # ptrace without sudo
  # File does not exist?
  #echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
  # bigcore.exp: permission denied.
  #echo | sudo tee /proc/sys/kernel/core_pattern

script: |
  cd "$TRAVIS_BUILD_DIR/_build/gdb"
  # Way more tests fail when running in parallel...
  #sudo make -j"$(nproc)" check
  # We cannot silence this to /dev/null, or else it would run for 10 minutes
  # without stdout, and Travis would kill it.
  sudo make check
  status=$?
  # This would blow up the log size.
  # The only way to see it would be to configure artifact upload.
  #cat testsuite/gdb.log
  echo '### START gdb.sum ###'
  grep -v '^PASS' testsuite/gdb.sum
  echo '### END gdb.sum ###'
  # In a subshell, otherwise the Travis build errors instead of fail.
  (exit $status)
